param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateSet('development', 'dev', 'production', 'prod', 'auto')]
    [string]$Environment
)

$selected = switch ($Environment.ToLowerInvariant()) {
    'dev' { 'development' }
    'prod' { 'production' }
    default { $Environment.ToLowerInvariant() }
}

$workspace = Split-Path -Parent $PSScriptRoot
$webEnvironmentFile = Join-Path $workspace 'web/.env.local'
$miniappEnvironmentFile = Join-Path $workspace 'miniapp/environment.js'
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)

$webProxyTarget = if ($selected -eq 'production') {
    'https://api.nkucare.cloud'
} else {
    'http://127.0.0.1:8080'
}

$webContent = @(
    '# Generated by scripts/switch-environment.ps1. Do not commit this file.'
    "VITE_ACTIVE_ENVIRONMENT=$selected"
    'VITE_API_BASE_URL=/api'
    "VITE_DEV_API_PROXY_TARGET=$webProxyTarget"
) -join "`n"

$miniappContent = @(
    '// Generated by scripts/switch-environment.ps1. Allowed values: development, production, auto.'
    "export const API_ENVIRONMENT = '$selected'"
) -join "`n"

[System.IO.File]::WriteAllText($webEnvironmentFile, $webContent + "`n", $utf8WithoutBom)
[System.IO.File]::WriteAllText($miniappEnvironmentFile, $miniappContent + "`n", $utf8WithoutBom)

Write-Host "Environment switched to: $selected"
Write-Host "Web development proxy: $webProxyTarget"
if ($selected -eq 'auto') {
    Write-Host 'Mini program: develop -> local API; trial/release -> production API'
} else {
    Write-Host "Mini program API: $selected"
}
Write-Host 'Restart the Vite development server and recompile the mini program for the change to take effect.'
